; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = 
	jgromes/RadioLib@^6.2.0
	mikalhart/TinyGPSPlus@^1.0.3
	bblanchon/ArduinoJson@^7.0.0
board_build.filesystem = littlefs
board_build.flash_size = 8MB
board_build.partitions = partitions_8MB_bigfs.csv
build_flags = 
	-DBOARD_HAS_PSRAM
